apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  namespace: jenkins
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container
        image: hagert/app:latest  
        ports:
        - containerPort: 80